name: GitHub Pages

on:
  push:
    branches:
      - main 
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Dart
        uses: dart/setup-dart@v2
        with:
          sdk: '3.0.0'

      - name: Install dependencies
        run: dart pub get
        
      - name: Build
        run: flutter build web --web-renderer html --base-href "/deploy-demo/"

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web  
